/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SketchesSplatRouteImport } from './routes/sketches.$'
import { Route as SketchesPixelSortingSplatRouteImport } from './routes/sketches.pixel-sorting.$'
import { Route as SketchesFlowFieldSplatRouteImport } from './routes/sketches.flow-field.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchesSplatRoute = SketchesSplatRouteImport.update({
  id: '/sketches/$',
  path: '/sketches/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchesPixelSortingSplatRoute =
  SketchesPixelSortingSplatRouteImport.update({
    id: '/sketches/pixel-sorting/$',
    path: '/sketches/pixel-sorting/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const SketchesFlowFieldSplatRoute = SketchesFlowFieldSplatRouteImport.update({
  id: '/sketches/flow-field/$',
  path: '/sketches/flow-field/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sketches/$': typeof SketchesSplatRoute
  '/sketches/flow-field/$': typeof SketchesFlowFieldSplatRoute
  '/sketches/pixel-sorting/$': typeof SketchesPixelSortingSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sketches/$': typeof SketchesSplatRoute
  '/sketches/flow-field/$': typeof SketchesFlowFieldSplatRoute
  '/sketches/pixel-sorting/$': typeof SketchesPixelSortingSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sketches/$': typeof SketchesSplatRoute
  '/sketches/flow-field/$': typeof SketchesFlowFieldSplatRoute
  '/sketches/pixel-sorting/$': typeof SketchesPixelSortingSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sketches/$'
    | '/sketches/flow-field/$'
    | '/sketches/pixel-sorting/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sketches/$'
    | '/sketches/flow-field/$'
    | '/sketches/pixel-sorting/$'
  id:
    | '__root__'
    | '/'
    | '/sketches/$'
    | '/sketches/flow-field/$'
    | '/sketches/pixel-sorting/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SketchesSplatRoute: typeof SketchesSplatRoute
  SketchesFlowFieldSplatRoute: typeof SketchesFlowFieldSplatRoute
  SketchesPixelSortingSplatRoute: typeof SketchesPixelSortingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches/$': {
      id: '/sketches/$'
      path: '/sketches/$'
      fullPath: '/sketches/$'
      preLoaderRoute: typeof SketchesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches/pixel-sorting/$': {
      id: '/sketches/pixel-sorting/$'
      path: '/sketches/pixel-sorting/$'
      fullPath: '/sketches/pixel-sorting/$'
      preLoaderRoute: typeof SketchesPixelSortingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches/flow-field/$': {
      id: '/sketches/flow-field/$'
      path: '/sketches/flow-field/$'
      fullPath: '/sketches/flow-field/$'
      preLoaderRoute: typeof SketchesFlowFieldSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SketchesSplatRoute: SketchesSplatRoute,
  SketchesFlowFieldSplatRoute: SketchesFlowFieldSplatRoute,
  SketchesPixelSortingSplatRoute: SketchesPixelSortingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
